---
apiVersion: v1
kind: Service
metadata:
  name: polaris-prometheus
spec:
  ports:
    - name: polaris-prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: polaris-pushgateway
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: polaris-prometheus
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polaris-prometheus
  name: polaris-prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: polaris-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: polaris-prometheus
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - /root/prometheus/prometheus --config.file=/root/prometheus/prometheus.yml
              --web.enable-lifecycle --web.enable-admin-api
          image: ccr.ccs.tencentyun.com/polaris_mesh/polaris-prometheus:1.2
          imagePullPolicy: Always
          name: polaris-prometheus
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
        - command:
            - /bin/bash
            - -c
            - /root/pushgateway/pushgateway --web.enable-lifecycle --web.enable-admin-api
          image: ccr.ccs.tencentyun.com/polaris_mesh/polaris-pushgateway:1.1.0
          imagePullPolicy: Always
          name: polaris-pushgateway
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
      restartPolicy: Always
