name: DockerImage

on:
  workflow_dispatch:
    inputs:
      docker_repository:
        description: 'docker repository for polaris'
        required: true
      docker_tag:
        description: 'docker image tag for polaris'
        required: true
      docker_username:
        description: 'docker username for login'
        required: true
      docker_password:
        description: 'docker password for login'
        required: true

jobs:
  release:
    name: Release Polaris Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
        exclude:
          - goos: linux
            goarch: arm64
    steps:
      - name: Build
        id: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          DOCKER_REPOSITORY: ${{ github.event.inputs.docker_repository }}
          DOCKER_TAG: ${{ github.event.inputs.docker_tag }}
          DOCKER_USER: ${{ github.event.inputs.docker_username }}
          DOCKER_PASS: ${{ github.event.inputs.docker_password }}
        run: |
          bash build_docker.sh ${DOCKER_REPOSITORY} ${DOCKER_TAG} ${DOCKER_USER} ${DOCKER_PASS}
