name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

# Always force the use of Go modules
env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Setup the environment.
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      # Checkout latest code
      - name: Checkout repo
        uses: actions/checkout@v2

      # Execute vert check
      - name: Vert check
        run: bash vert.sh -install && bash vert.sh

      # Compile
      - name: Build server
        run: bash build.sh
        
      # Run unit tests
      - name: run tests
        run: |
          cd ./naming/cache
          go test -v
          cd ./plugin/ratelimit/tokenBucket
          go test -v
          cd ./store/defaultStore
          go test -v
          
      # Run interface tests
      - name: run interface tests
        run: |
          cd ./polaris-server-release*
          chmod +x ./tool/*.sh
          ./tool/install.sh
          cd ../test
          go test -count=1 -v
          cd ../polaris-server-release*
          ./tool/uninstall.sh